# Generated by Django 3.1.4 on 2020-12-13 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_profile_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="link",
            field=models.CharField(default="https://meet.google.com/", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="classroom",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="api.profile",
            ),
        ),
    ]
