# Generated by Django 3.1.4 on 2020-12-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201213_0246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['period']},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='period',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
